#!/usr/bin/env bash
# my www task
display_subdomain_info() {
    local domain=$1
    local subdomain=$2

    # Get the DNS record type and destination for the subdomain
    record_type=$(dig +short $subdomain.$domain | awk '{print $4}')
    destination=$(dig +short $subdomain.$domain | awk '{print $5}')

    # Output the information
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # Display information for default subdomains
    display_subdomain_info $domain www
    display_subdomain_info $domain lb-01
    display_subdomain_info $domain web-01
    display_subdomain_info $domain web-02
else
    # Display information for the specified subdomain
    display_subdomain_info $domain $subdomain
fi
