#!/usr/bin/env bash
# my 1-100 Fizz Buzz
for ((i=1; i<=100; i++))
do
        if [ $((i%3)) == 0 ];
        then
                echo "Fizz"
        elif [ $((i%5)) == 0 ];
        then
                echo "Buzz"
        else
                echo $i
        fi
done
