#!/usr/bin/env bash
#to print Best School 10 times using while
ff=1
while [ $ff -le 10 ]
do
	if [ $ff == 4 ];
	then
		echo "bad luck"
	elif [ $ff == 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((ff++))
done
