#!/usr/bin/env bash
#to print Best School 10 times using while
ff=1
while [ $ff -le 20 ]
do
case $ff in
4)
echo "4"
echo "bad luck from China"
;;
9)
echo "9"
echo "bad luck from Japan"
;;
17)
echo "17"
echo "bad luck from Italy"
;;
*)
echo "$ff"
;;
esac
((ff++))
done
