#!/usr/bin/env bash
# Display all active IPv4 IPs on the machine
ifconfig | grep "inet addr:" | cut -d ':' -f 2- | cut -d ' ' -f 1
#active IPv4 IPs on the machine
#ifconfig | grep -Po 'inet addr:\K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
